### ISSUE TITLE
The url in gamgee/.travis_scripts/cmake.sh is invalid now

### ISSUE THREAD

**Issue by lucklove** [broadinstitute/gamgee#405]
got 403 while
wget http://www.broadinstitute.org/~carneiro/travis/cmake_3.1.0-rc1-1_amd64.deb
I try the following steps to update cmake(to 2.8.12):
- sudo add-apt-repository -y ppa:andykimpe/cmake
- sudo apt-get -qq update
- sudo apt-get install cmake    
Maybe this is also helpful to you.   
see https://github.com/lucklove/ahttpd/blob/master/.travis.yml

**Comment by lucklove** [comment]
Ok now, sorry for bother.

**Comment by jmthibault79** [comment]
Thank you for pointing this out @lucklove !

When you saw that it was working again, it was because you inspired us to recover the file.  We have now moved it to a more appropriate location.
